name: Discord Notifications

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, closed, merged]
    branches: [ main ]
  workflow_run:
    workflows: ["CI/CD Pipeline", "Code Quality", "Security"]
    types: [completed]
    branches: [ main ]

jobs:
  notify:
    name: Send Discord Notification
    runs-on: ubuntu-latest
    if: always() # Executa mesmo se outros jobs falharem
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set notification content
      id: notification
      run: |
        # Determinar o tipo de evento e status
        if [ "${{ github.event_name }}" = "push" ]; then
          EVENT_TYPE="🚀 **Commit no Main**"
          STATUS_EMOJI="✅"
          STATUS_TEXT="Commit realizado com sucesso"
        elif [ "${{ github.event_name }}" = "pull_request" ]; then
          if [ "${{ github.event.action }}" = "opened" ]; then
            EVENT_TYPE="📝 **Pull Request Aberto**"
            STATUS_EMOJI="🆕"
            STATUS_TEXT="Nova PR criada"
          elif [ "${{ github.event.action }}" = "closed" ] && [ "${{ github.event.pull_request.merged }}" = "true" ]; then
            EVENT_TYPE="🔀 **Pull Request Merged**"
            STATUS_EMOJI="✅"
            STATUS_TEXT="PR foi mergeada com sucesso"
          elif [ "${{ github.event.action }}" = "closed" ]; then
            EVENT_TYPE="❌ **Pull Request Fechada**"
            STATUS_EMOJI="❌"
            STATUS_TEXT="PR foi fechada sem merge"
          fi
        elif [ "${{ github.event_name }}" = "workflow_run" ]; then
          if [ "${{ github.event.workflow_run.conclusion }}" = "success" ]; then
            EVENT_TYPE="🔄 **Workflow Executado**"
            STATUS_EMOJI="✅"
            STATUS_TEXT="Workflow executado com sucesso"
          elif [ "${{ github.event.workflow_run.conclusion }}" = "failure" ]; then
            EVENT_TYPE="🔄 **Workflow Falhou**"
            STATUS_EMOJI="❌"
            STATUS_TEXT="Workflow falhou"
          else
            EVENT_TYPE="🔄 **Workflow Executado**"
            STATUS_EMOJI="⚠️"
            STATUS_TEXT="Workflow executado com status: ${{ github.event.workflow_run.conclusion }}"
          fi
        fi
        
        # Criar mensagem formatada
        cat << EOF > notification.json
        {
          "embeds": [
            {
              "title": "${EVENT_TYPE}",
              "description": "${STATUS_EMOJI} ${STATUS_TEXT}",
              "color": ${{ github.event_name == 'push' && '65280' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true && '65280') || (github.event.workflow_run.conclusion == 'success' && '65280') || '16711680' }},
              "fields": [
                {
                  "name": "📁 Repositório",
                  "value": "${{ github.repository }}",
                  "inline": true
                },
                {
                  "name": "🌿 Branch",
                  "value": "${{ github.ref_name }}",
                  "inline": true
                },
                {
                  "name": "👤 Autor",
                  "value": "${{ github.actor }}",
                  "inline": true
                },
                {
                  "name": "🔗 Commit",
                  "value": "[${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})",
                  "inline": false
                },
                {
                  "name": "📝 Mensagem do Commit",
                  "value": "${{ github.event.head_commit.message || github.event.pull_request.title || 'N/A' }}",
                  "inline": false
                }
              ],
              "footer": {
                "text": "GitHub Actions • ${{ github.workflow }}",
                "icon_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
              },
              "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
            }
          ]
        }
        EOF
        
        echo "notification_content=$(cat notification.json)" >> $GITHUB_OUTPUT
    
    - name: Send Discord notification
      if: env.DISCORD_WEBHOOK_URL != ''
      run: |
        curl -H "Content-Type: application/json" \
             -X POST \
             -d @notification.json \
             ${{ secrets.DISCORD_WEBHOOK_URL }}
    
    - name: Fallback notification (if webhook not configured)
      if: env.DISCORD_WEBHOOK_URL == ''
      run: |
        echo "⚠️ DISCORD_WEBHOOK_URL não configurado!"
        echo "Para configurar:"
        echo "1. Vá para Settings > Secrets and variables > Actions"
        echo "2. Adicione uma nova secret chamada 'DISCORD_WEBHOOK_URL'"
        echo "3. Cole a URL do webhook do seu servidor Discord"
        echo ""
        echo "Conteúdo da notificação que seria enviada:"
        cat notification.json
