name: Security

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 2 * * 1' # Run every Monday at 2 AM

jobs:
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run npm audit
      run: |
        npm audit --audit-level high --json > audit-results.json || true
        npm audit --audit-level high || echo "Audit completed with issues"
    
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high
    
    - name: Upload audit results
      uses: actions/upload-artifact@v4
      with:
        name: audit-results
        path: audit-results.json
        retention-days: 30
    
    - name: Check for secrets
      run: |
        # Instalar TruffleHog usando a versão mais recente disponível
        echo "🔍 Instalando TruffleHog..."
        
        # Obter a versão mais recente
        LATEST_VERSION=$(curl -s https://api.github.com/repos/trufflesecurity/trufflehog/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
        echo "📦 Versão mais recente: $LATEST_VERSION"
        
        # Baixar o arquivo correto baseado na versão
        wget "https://github.com/trufflesecurity/trufflehog/releases/download/${LATEST_VERSION}/trufflehog_${LATEST_VERSION#v}_linux_amd64.tar.gz" -O trufflehog.tar.gz
        
        # Extrair e configurar
        tar -xzf trufflehog.tar.gz
        chmod +x trufflehog
        
        echo "✅ TruffleHog instalado com sucesso"
        
        # Executar scan do repositório inteiro
        echo "🔍 Executando scan de secrets..."
        ./trufflehog filesystem . --only-verified --format json --output trufflehog-results.json || echo "TruffleHog scan completed with findings"
        
        # Mostrar resumo dos resultados
        if [ -f trufflehog-results.json ]; then
          echo "📊 TruffleHog scan results:"
          cat trufflehog-results.json | head -20
        else
          echo "✅ Nenhum secret encontrado pelo TruffleHog"
        fi
    
    - name: Upload TruffleHog results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: trufflehog-results
        path: trufflehog-results.json
        retention-days: 30
